baseURL = "https://uniharsh.com/"
languageCode = "en-us"
title = "Harshit Kaushik"
theme = "hugo-PaperMod-master"

[author]
name = "Harshit Kaushik"

[params]
headTitle = "Harshit Kaushik"
mainSections = ["posts", "poems", "software", "music"]
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
extraCSSFiles = ["css/harshit.me.css"]
googleAnalyticsID = "G-DGP3KYZQFF"

[[params.socials]]
name = "About me"
link = "https://www.linkedin.com/in/harshit-kaushik-21845b21b/"

[[params.socials]]
name = "Github"
link = "https://github.com/HarshitKaushik"

[[params.socials]]
name = "Twitter"
link = "https://twitter.com/DragIsLit"