baseURL = "https://uniharsh.com/"

defaultContentLanguage = 'en'
languageCode = "en-us"
# [languages]
#   [languages.en]
#     title = 'Harshit Kaushik'
#     weight = 1
#     [languages.en.params]
#   [languages.hi]
#     title = 'हर्षित'
#     weight = 2
#     [languages.fr.params]

title = "Harshit Kaushik"
theme = "hugo-PaperMod-master"

[author]
name = "Harshit Kaushik"

[params]
headTitle = "Harshit Kaushik"
mainSections = ["posts", "poems", "software", "music"]
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
extraCSSFiles = ["css/harshit.me.css"]
googleAnalyticsID = "G-DGP3KYZQFF"

[[params.socials]]
name = "About me"
link = "https://www.linkedin.com/in/harshit-kaushik-21845b21b/"

[[params.socials]]
name = "Github"
link = "https://github.com/HarshitKaushik"

[[params.socials]]
name = "Twitter"
link = "https://twitter.com/DragIsLit"